### ISSUE TITLE
NanoHat OLED: bug in bakebit_nanohat_oled.py

### ISSUE THREAD

**Issue by safforddr** [friendlyarm/BakeBit#4]
I have a nanopi neo-plus2 with NanoHat OLED, running the latest ubuntu image 
(nanopi-neo-plus2_ubuntu-core-xenial_4.11.2_20170630.img).

I compiled the latest BakeBit_20170707 and NanoHatOLED_20170707, 
and also tried compiling from the latest git. In all cases, the initial 
display (page_index 0) works fine, but when I try to display page_index 1
(by pressing the middle button), bakebit_nanohat_oled.py exits on line 156
when it calls draw.text on the IP address field. 

After troubleshooting, I found that this is due to the IP value having
a trailing \n. By modifying line 144 to:
	cmd = "hostname -I | cut -d\' \' -f1 | tr -d \'\\n\'"
which deletes the trailing newline, everything works fine.

**Comment by friendlyarm** [comment]
Thank you very much, This bug has been fixed.
